In [1]:
import numpy as np

List vs Numpy - Time Taken

In [2]:
from time import process_time

Time taken by a list

In [12]:
python_list = [i for i in range(1000000)]

start_time =  process_time()

python_list = [i + 5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.015625


In [13]:
np_array = np.array([i for i in range(1000000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.0


In [16]:
#list
list1 = [1,2,3,4,5]
print(list1)
type(list1)


[1, 2, 3, 4, 5]


list

In [17]:
np_array1 = np.array([1,2,3,4,5])
print(np_array1)
type(np_array1)

[1 2 3 4 5]


numpy.ndarray

In [18]:
#Creating a 1 dim array
a = np.array([1,2,3,4])
print(a)
print(a.shape)

[1 2 3 4]


In [21]:
#Creating more a 1 dim array
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)
print(b.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [22]:
c = np.array([(1,2,3,4),(5,6,7,8)], dtype= float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Inicial Placeholds in numpy array

In [27]:
#create a numpy array of zeros
x = np.zeros((4,5))
print(x)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [25]:
#create a numpy array of ones
y = np.ones((3,3), dtype=int)
print(y)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [28]:
#create a numpy array of a particular value
z = np.full((5,4), "casa")
print(z)

[['casa' 'casa' 'casa' 'casa']
 ['casa' 'casa' 'casa' 'casa']
 ['casa' 'casa' 'casa' 'casa']
 ['casa' 'casa' 'casa' 'casa']
 ['casa' 'casa' 'casa' 'casa']]


In [29]:
#create an identity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [30]:
#create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.56561877 0.30965974 0.87860208 0.6092795 ]
 [0.44476236 0.76473298 0.05144972 0.9037725 ]
 [0.76053815 0.75622328 0.09790989 0.10669913]]


In [32]:
#creata random integer values array with specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[96 75 72 90 76]
 [67 28 13 65 59]
 [34 67 46 62 32]]


In [37]:
#array of evenly spaced values --> specifying the number of values requiredd
d = np.linspace(-100,100,20)
print(d)

[-100.          -89.47368421  -78.94736842  -68.42105263  -57.89473684
  -47.36842105  -36.84210526  -26.31578947  -15.78947368   -5.26315789
    5.26315789   15.78947368   26.31578947   36.84210526   47.36842105
   57.89473684   68.42105263   78.94736842   89.47368421  100.        ]


In [36]:
#array of evenly spaced values --> specifying the step
e = np.arange(-100,100,20)
print(e)

[-100  -80  -60  -40  -20    0   20   40   60   80]


In [39]:
#convert a listo to a numpy array
list2 = [10,20,30,40,40,50]
np_array3 = np.asarray(list2)

print(np_array3)
print(type(np_array3))

[10 20 30 40 40 50]
<class 'numpy.ndarray'>


Analysing a numpy array

In [40]:
c = np.random.randint(10,90,(5,5))
print(c)

[[82 79 19 60 44]
 [56 12 42 29 30]
 [72 65 88 77 46]
 [47 86 30 43 42]
 [73 30 63 30 33]]


In [41]:
#array dimension
print(c.shape)

(5, 5)


In [42]:
#number of dimensions
print(c.ndim)

2


In [43]:
#number of elements in an array
print(c.size)

25


In [44]:
#checking the data type of the values in the array
print(c.dtype)

int32


Mathematical operations on a np array

In [45]:
list_a = [1,2,3,4,5]
list_b = [6,7,8,9,10]

print(list_a + list_b) #concatenate or join two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [53]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

print(a)
print()
print(b)
print()

[[6 7 3]
 [8 3 5]
 [9 0 1]]

[[11 14 15]
 [11 19 14]
 [13 17 14]]



In [56]:
print(a+b)
print()
print(a-b)
print()
print(a*b)
print()
print(a/b)
print()
print(a//b)
print()
print(a%b)

[[17 21 18]
 [19 22 19]
 [22 17 15]]

[[ -5  -7 -12]
 [ -3 -16  -9]
 [ -4 -17 -13]]

[[ 66  98  45]
 [ 88  57  70]
 [117   0  14]]

[[0.54545455 0.5        0.2       ]
 [0.72727273 0.15789474 0.35714286]
 [0.69230769 0.         0.07142857]]

[[0 0 0]
 [0 0 0]
 [0 0 0]]

[[6 7 3]
 [8 3 5]
 [9 0 1]]


In [59]:
print(np.add(a,b))
print()
print(np.subtract(a,b))
print()
print(np.multiply(a,b))
print()
print(np.divide(a,b))
print()
print(np.divmod(a,b))

[[17 21 18]
 [19 22 19]
 [22 17 15]]

[[ -5  -7 -12]
 [ -3 -16  -9]
 [ -4 -17 -13]]

[[ 66  98  45]
 [ 88  57  70]
 [117   0  14]]

[[0.54545455 0.5        0.2       ]
 [0.72727273 0.15789474 0.35714286]
 [0.69230769 0.         0.07142857]]

(array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]]), array([[6, 7, 3],
       [8, 3, 5],
       [9, 0, 1]]))


Array Manipulation

In [60]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[9 9 6]
 [4 1 1]]
(2, 3)


In [62]:
#transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[9 4]
 [9 1]
 [6 1]]
(3, 2)


In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

In [63]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[9 4]
 [9 1]
 [6 1]]
(3, 2)


In [64]:
#reshape
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[8 3 5]
 [0 7 6]]
(2, 3)


In [65]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[8 3]
 [5 0]
 [7 6]]
(3, 2)
