In [1]:
import numpy as np

Dot Product of 2 Vectors

In [2]:
a = np.array([2,3])
b = np.array([4,4])

a_dot_b = np.dot(a,b)
print(a_dot_b)

20


In [4]:
c = np.array([40,20,35])
d = np.array([53,24,68])

c_dot_d = np.dot(c,d)
print(c_dot_d)

4980


Cross Product of 2 Vectors

In [8]:
a = np.array([2,3])
b = np.array([4,4])

a_croos_b = np.cross(a,b)
print(a_croos_b)

[-4  0  0]


In [9]:
a = np.array([2,3,0])
b = np.array([4,4,0])

a_croos_b = np.cross(a,b)
print(a_croos_b)

[ 0  0 -4]


In [7]:
e = np.array([5,10,20])
f = np.array([18,32,50])

e_cross_f = np.cross(e,f)
print(e_cross_f)

[-140  110  -20]


Projection of 'a' vector on 'v' vector


In [12]:
a = np.array([2,5])
v = np.array([8,-6])

magnitude_v_vector = np.sqrt(sum(v**2))

proj_of_a_on_v= (np.dot(a,v/magnitude_v_vector**2))*v
proj_of_a_on_v

array([-1.12,  0.84])

In [13]:
a = np.array([23,45,62])
v = np.array([45,82,67])

magnitude_v_vector = np.sqrt(sum(v**2))

proj_of_a_on_v= (np.dot(a,v/magnitude_v_vector**2))*v
proj_of_a_on_v

array([30.18242937, 54.99909352, 44.93828373])