In [2]:
import numpy as np

Creating a matrix using a numpy

In [9]:
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)
print('\nMatrix shape:')
print(matrix_1.shape)

[[2 3]
 [6 7]]

Matrix shape:
(2, 2)


In [12]:
matrix_2 = np.array([[10,35,43],[66,-43,-51],[26,6,-79]])
print(matrix_2)
print('\nMatrix shape:')
print(matrix_2.shape)

[[ 10  35  43]
 [ 66 -43 -51]
 [ 26   6 -79]]

Matrix shape:
(3, 3)


Creatring Matrices with Random Values

In [14]:
random_matrix = np.random.rand(4,3)
print(random_matrix)

[[0.43940498 0.42196326 0.77891209]
 [0.5594989  0.24383628 0.18547596]
 [0.19244966 0.81456675 0.81504249]
 [0.94360501 0.64218931 0.46929876]]


In [15]:
# Creating a matrix with random integers
random_integer_matrix = np.random.randint(100,size=(4,5))
print(random_integer_matrix)

[[29 64 93 48 56]
 [16 30 60 12 11]
 [85 46 72 42 65]
 [70 92 84 62 69]]


Matrix with all the values as 1

In [22]:
matrix_3 = np.ones((2,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [23]:
matrix_3 = np.ones((2,3), dtype=int)
print(matrix_3)

[[1 1 1]
 [1 1 1]]


Null Matrix or Zero Matrix

In [25]:
null_matrix = np.zeros((4,4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [28]:
null_matrix = np.zeros((7,3), dtype=int)
print(null_matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


Identity Matrix

In [29]:
identity_matrix = np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
identity_matrix = np.eye(5,4, dtype=int)
print(identity_matrix)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]


Transpose Matrix

In [31]:
# Matrix with random integers
a = np.random.randint(100, size = (4,5))
print(a)

[[88 81 49 22 39]
 [94 26 23 57 49]
 [67  5 30 98 60]
 [43 44 46 63 30]]


In [33]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[88 94 67 43]
 [81 26  5 44]
 [49 23 30 46]
 [22 57 98 63]
 [39 49 60 30]]


In [34]:
a.T

array([[88, 94, 67, 43],
       [81, 26,  5, 44],
       [49, 23, 30, 46],
       [22, 57, 98, 63],
       [39, 49, 60, 30]])