In [1]:
import numpy as np

Matrix Adittion

In [5]:
# Creating two matrices

a = np.array([[2,3],[4,5]])
b = np.array([[6,7],[8,9]])

In [7]:
print(a)
print("\nMatrix Shape")
print(a.shape)

[[2 3]
 [4 5]]

Matrix Shape
(2, 2)


In [8]:
print(b)
print("\nMatrix Shape")
print(b.shape)

[[6 7]
 [8 9]]

Matrix Shape
(2, 2)


Adding two matrices

In [11]:
sum = a + b
print(sum)

[[ 8 10]
 [12 14]]


In [19]:
# Creating two matrices with random values
matrix_1 = np.random.randint(10, size = (3,3))
matrix_2 = np.random.randint(20, size = (3,3))

print('Matrix 1:\n', matrix_1,'\n\n','Matrix 2:\n', matrix_2)

Matrix 1:
 [[1 8 0]
 [7 7 3]
 [8 5 7]] 

 Matrix 2:
 [[ 0 12 13]
 [ 9  0 16]
 [ 3 17  6]]


In [21]:
sum =  matrix_1 + matrix_1

print('Sum of matrices:\n', sum)

Sum of matrices:
 [[ 2 16  0]
 [14 14  6]
 [16 10 14]]


Matrix Subtaction

In [28]:
a = np.array([[2,1],[4,3]])
b = np.array([[6,0],[7,9]])

difference = a - b
print(a,'\n\n',b, '\n')
print(difference)

[[2 1]
 [4 3]] 

 [[6 0]
 [7 9]] 

[[-4  1]
 [-3 -6]]


Multiplying a Matrix by a Scaler

In [31]:
x = 5
y = np.random.randint(10, size = (4,4))
print(y)

[[4 1 4 7]
 [9 1 7 2]
 [5 2 0 3]
 [3 0 2 7]]


In [32]:
product = np.multiply(x,y)
print(product)

[[20  5 20 35]
 [45  5 35 10]
 [25 10  0 15]
 [15  0 10 35]]


Multiplying two Matrices

In [33]:
# Creating two Matrices with random values
matrix_3 = np.random.randint(5, size = (3,3))
matrix_4 = np.random.randint(5, size = (3,4))

In [36]:
print("Matrix 3:\n", matrix_3, "\n\nMatrix 4:\n", matrix_4)

Matrix 3:
 [[2 4 1]
 [1 1 0]
 [0 3 4]] 

Matrix 4:
 [[4 0 4 2]
 [4 1 2 1]
 [0 2 1 4]]


In [39]:
product = np.dot(matrix_3, matrix_4)
print(product)
print('\n')
print(product.shape)

[[24  6 17 12]
 [ 8  1  6  3]
 [12 11 10 19]]


(3, 4)


Element wise Matrix Multiplication

In [49]:
# Creating two Matrices with random values
matrix_5 = np.random.randint(1,5, size = (3,3))
matrix_6 = np.random.randint(1,5, size = (3,3))

In [50]:
print("Matrix 5:\n", matrix_5, "\n\nMatrix 6:\n", matrix_6)

Matrix 5:
 [[3 1 1]
 [4 4 2]
 [3 1 1]] 

Matrix 6:
 [[1 2 2]
 [2 2 4]
 [4 1 1]]


In [51]:
product = np.multiply(matrix_5, matrix_6)
print(product)

[[ 3  2  2]
 [ 8  8  8]
 [12  1  1]]
